# Generated by Django 4.1.6 on 2023-02-17 20:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210414_1718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'ordering': ['-value'], 'verbose_name': 'Discount', 'verbose_name_plural': 'Discounts'},
        ),
        migrations.AlterModelOptions(
            name='orderline',
            options={'verbose_name': 'Order line', 'verbose_name_plural': 'Order lines'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title', '-year'], 'verbose_name': 'Product', 'verbose_name_plural': 'Goods'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['id'], 'verbose_name': 'Chapter', 'verbose_name_plural': 'Sections'},
        ),
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(max_length=10, verbose_name='Coupon code'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='value',
            field=models.IntegerField(help_text='In percentages', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Amount of discount'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(blank=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_order',
            field=models.DateTimeField(auto_now_add=True, verbose_name='order date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_send',
            field=models.DateTimeField(blank=True, null=True, verbose_name='departure date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=70, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='need_delivery',
            field=models.BooleanField(verbose_name='Delivery required'),
        ),
        migrations.AlterField(
            model_name='order',
            name='notice',
            field=models.TextField(blank=True, verbose_name='Order note'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=70, verbose_name='Telephone'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'New order'), ('APR', 'Confirmed'), ('PAY', 'Paid'), ('CNL', 'Cancelled')], default='NEW', max_length=3, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='count',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cast',
            field=models.TextField(verbose_name='Cast'),
        ),
        migrations.AlterField(
            model_name='product',
            name='country',
            field=models.CharField(max_length=70, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Date added'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='director',
            field=models.CharField(max_length=70, verbose_name='Director'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='play',
            field=models.IntegerField(blank=True, help_text='В seconds', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.section', verbose_name='Chapter'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=70, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2023)], verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(help_text='Here you need to enter the name of the section', max_length=70, unique=True, verbose_name='Section name'),
        ),
    ]
